# utf-8
# 基础配置模板

[一般的]
旁路系统 = true
doh-server = https://dns.alidns.com/dns-query,https://doh.pub/dns-query
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/24, 192.168.0.0/24, 192.168.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/24, 255.255.255.255/32
DNS 服务器 = 系统
IPv6 = false

[规则]
# 广告广告
DOMAIN-SET,https://anti-ad.net/surge2.txt,拒绝

# 全球全球加速
规则集, https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWList.list, 代理

# 国内直连
规则集, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/Shadowrocket/China/China.list, 直连

GEOIP, CN, DIRECT
最终代理

[主持人]

[URL 重写]

[脚本]

[MITM]
ca-passphrase = 0
ca-p12 = 0
启用 = true
