# utf-8
# 2026-09-22 12:00:00

[一般的]
旁路系统 = true
doh-server = https://dns.alidns.com/dns-query,https://dns.pub/dns-query
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.16, 172.16.0.0/12, 192.168.0.0/24, 192.168.0.0/16, 192.168.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/24, 255.255.255.255/32
DNS 服务器 = 系统
IPv6 = true

[规则]
# 广告广告
DOMAIN-SET,https://anti-ad.net/surge2.txt,拒绝

# 币安强制直连
域名后缀, binance.com, 直接
域名后缀, binance.cc, 直接
域名后缀, binance.me, 直接
域名后缀, bntx.cc, 直接

# TikTok 最新免拔卡解锁分流
规则集, https://raw.githubusercontent.com/Semporia/TikTok-Unlock/master/Shadowrocket/TikTok.list, 代理

# 全球全球加速
规则集, https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWList.list, 代理

# 中国国内直连
规则集, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/China/China.list, 直接

GEOIP, CN, DIRECT
最终代理

[主持人]

[URL 重定向]
# Google 搜索国内内协重定向
^https?:\/\/(\w+\.)?g\.cn https://www.google.com 302
^https?:\/\/(\w+\.)?google\.cn https://www.google.com 302

[脚本]

[MITM]
主机名 = *.google.cn,*.googlevideo.com,mp.weixin.qq.com,gs-loc.apple.com,gs-loc.cn.apple.com,gsp-ssl.ls.apple.com,bluedot.is.autonavi.com,gds.alabadns.com,*.tiktokv.com,*.byteoverseas.com,*.tik-tokapi.com

ca-passphrase = Ptwvghgm
ca-p12 = 0
启用 = true
